# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.SmallIntegerField(default=18, verbose_name='年龄'),
        ),
    ]
